### ISSUE TITLE
注册表bug

### ISSUE THREAD

**Issue by freesoft0000** [dragonflylee/WimHelper#1]
Server.reg  Synaptics.reg两个注册表内容都失去了换行。
------------------------------------------------------------
补充：不是失去了换行，是这个两个文件换行符不是pc，所以记事本打开没有换行。

**Comment by dragonflylee** [comment]
@freesoft0000 只是变成了只有 CR 换行符，并非失去了换行，您可用Notepad2之类的工具查看

**Comment by freesoft0000** [comment]
之后通过其它文本编辑器看到了。转换一个换行符就行了。
希望下次更新的时候修正一下。
谢谢！

**Comment by dragonflylee** [comment]
@freesoft0000 已修正
