### ISSUE TITLE
你的系统不能下载任何商店里的应用？

### ISSUE THREAD

**Issue by ghost** [dragonflylee/WimHelper#2]
如题

**Comment by dragonflylee** [comment]
@allenchennnn 能否提供系统版本号和相关截图，经测试16299.214 专业版64位是可以正常下载商店应用的（今天修复了QQ、淘宝不能使用的问题）

**Comment by ghost** [comment]
16299.214 专业版32位，试着下载很多应用，都显示：
![image](https://user-images.githubusercontent.com/34701926/36149201-d15669de-10f9-11e8-9105-a74f11b72990.png)

**Comment by dragonflylee** [comment]
@allenchennnn 微信 for Windows 只支持x64架构，这个原版也是这样的

**Comment by ghost** [comment]
1.原版32位系统可以安装的呀。
2.不止微信是这样，随便点一个都是下载不了的。

**Comment by ghost** [comment]
包括原版系统自带的，比如：计算器，电视和电影，图片，微软翻译

**Comment by dragonflylee** [comment]
@allenchennnn 建议删除 C:\Windows\SoftwareDistribution 后重试，这边32位测试也正常

**Comment by ghost** [comment]
可以了，你的系统在哪发布的？求百度网盘共享。

**Comment by dragonflylee** [comment]
@allenchennnn https://www.itreping.com/windows/1505.html
